"""empty message

Revision ID: 22b5f826b3e5
Revises: 91523898ebb4
Create Date: 2024-01-14 16:29:53.850129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b5f826b3e5'
down_revision = '91523898ebb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_jual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harga_jual', schema=None) as batch_op:
        batch_op.drop_column('nama')

    # ### end Alembic commands ###
