"""empty message

Revision ID: 57a141fcf6bf
Revises: 
Create Date: 2024-01-02 03:26:00.725686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a141fcf6bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harga_jual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('tgl_berlaku', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('jumlah', sa.Float(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('belanja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('id_modal', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_modal'], ['modal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('belanja_rinci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_barang', sa.String(length=255), nullable=False),
    sa.Column('harga', sa.Float(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('belanja_id', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['belanja_id'], ['belanja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produksi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_belanja', sa.Integer(), nullable=False),
    sa.Column('jumlah_produksi', sa.Float(), nullable=False),
    sa.Column('tanggal_produksi', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_belanja'], ['belanja.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_produksi', sa.Integer(), nullable=False),
    sa.Column('id_harga', sa.Integer(), nullable=False),
    sa.Column('jumlah_penjualan', sa.Float(), nullable=False),
    sa.Column('tanggal_penjualan', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_harga'], ['harga_jual.id'], ),
    sa.ForeignKeyConstraint(['id_produksi'], ['produksi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jual')
    op.drop_table('produksi')
    op.drop_table('belanja_rinci')
    op.drop_table('belanja')
    op.drop_table('users')
    op.drop_table('modal')
    op.drop_table('harga_jual')
    # ### end Alembic commands ###
