"""empty message

Revision ID: 91523898ebb4
Revises: 8946ac464724
Create Date: 2024-01-14 14:57:23.656374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91523898ebb4'
down_revision = '8946ac464724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produksi', schema=None) as batch_op:
        batch_op.drop_column('nama')

    # ### end Alembic commands ###
