"""empty message

Revision ID: e75ab8385b53
Revises: 1023f74eebef
Create Date: 2024-01-14 00:18:34.882836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75ab8385b53'
down_revision = '1023f74eebef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pemodal', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modal', schema=None) as batch_op:
        batch_op.drop_column('is_pemodal')

    # ### end Alembic commands ###
